### PR TITLE
Parse JSON input before forwarding it

### LINKED ISSUE #12: Unable to make record links
When I attempt to make a record link:
```javascript
    let customerOrganization = null;
    let customerUser1 = null;

    customerOrganization = await db.create('organization', {
      name: 'Customer organization',
      type: ['customer']
    });
    console.log('created customer', customerOrganization)
    // created customer [
    //   {
    //     id: 'organization:id1az0rct82w9gw0vd7t',
    //     name: 'Customer organization',
    //     type: [ 'customer' ],
    //     updatedAt: '2023-09-23T16:24:32.941479Z'
    //   }
    // ]
    customerUser1 = await db.query(`
      INSERT INTO userAccount {
        firstName: $firstName,
        lastName: $lastName,
        email: $email,
        organization: $organization
      };
    `, {
      firstName: 'Customer',
      lastName: 'User1',
      email: 'test1@test.com',
      organization: customerOrganization[0].id
    })
    // Found 'organization:rxzhzkxhx7c0bmx6j2x8' for field `organization`, with record `userAccount:ki86v3aqoe8h9yvdq6o3`, but expected a record<organization>
    console.log('created user', customerUser1)
```
It doesn't work because it treats the ID as a string and not an actual record. This might be resolved by using `string::split` combined with `type::thing` but we shouldn't have to do that.

Because this is using the rust driver under the hood, its probably not handling the type in a way that works well for JS based platforms.

### PR DESCRIPTION
**Pull request by kearfy**
fixes #12

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -179,7 +179,10 @@ impl Surreal {
     pub async fn query(&self, sql: String, bindings: Option<Value>) -> Result<Value> {
         let mut response = match bindings {
             None => self.db.query(sql).await.map_err(err_map)?,
-            Some(b) => self.db.query(sql).bind(b).await.map_err(err_map)?,
+            Some(b) => {
+                let b = json(&b.to_string()).unwrap();
```
Comment (rushmorem) [inline src/lib.rs:183]: I know it's unlikely to run into an error here but it's possible. Kindly propagate it please.

File: src/lib.rs [hunk 2]
```diff
@@ -217,26 +220,31 @@ impl Surreal {
     #[napi]
     pub async fn create(&self, resource: String, data: Option<Value>) -> Result<Value> {
         let resource = Resource::from(resource);
-
-        let response = match data {
-            Some(d) => self.db.create(resource).content(d).await.map_err(err_map)?,
+		let response = match data {
             None => self.db.create(resource).await.map_err(err_map)?,
+            Some(d) => {
+                let d = json(&d.to_string()).unwrap();
```
Comment (rushmorem) [inline src/lib.rs:226]: I know it's unlikely to run into an error here but it's possible. Kindly propagate it please.

File: src/lib.rs [hunk 3]
```diff
@@ -250,7 +258,7 @@ impl Surreal {
                 .range((range.beg, range.end)),
             Err(_) => self.db.update(Resource::from(resource)),
         };
-        let data: Value = from_value(data)?;
+		let data = json(&data.to_string()).unwrap();
```
Comment (rushmorem) [inline src/lib.rs:261]: I know it's unlikely to run into an error here but it's possible. Kindly propagate it please.

**Review by rushmorem — APPROVED** [review]
